name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ai-rec-450910

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/ai-rec-450910/ai-se .
          docker push gcr.io/ai-rec-450910/ai-se

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image gcr.io/ai-rec-450910/ai-se \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --port 8080
